DECLARE @RN CHAR(10);
SET @RN='{}';
SELECT
    (SELECT TOP 1 AISE FROM Setting.Configuration WHERE AISE IS NOT NULL AND Radio_Name=@RN ORDER BY Date DESC) AS AISE,
    (SELECT TOP 1 AISF FROM Setting.Configuration WHERE AISF IS NOT NULL AND Radio_Name=@RN ORDER BY Date DESC) AS AISF,
    (SELECT TOP 1 EVSR FROM Setting.Configuration WHERE EVSR IS NOT NULL AND Radio_Name=@RN ORDER BY Date DESC) AS EVSR,
    (SELECT TOP 1 FFBL FROM Setting.Configuration WHERE FFBL IS NOT NULL AND Radio_Name=@RN ORDER BY Date DESC) AS FFBL,
    (SELECT TOP 1 FFEA FROM Setting.Configuration WHERE FFEA IS NOT NULL AND Radio_Name=@RN ORDER BY Date DESC) AS FFEA,
    (SELECT TOP 1 FFFC FROM Setting.Configuration WHERE FFFC IS NOT NULL AND Radio_Name=@RN ORDER BY Date DESC) AS FFFC,
    (SELECT TOP 1 FFLM FROM Setting.Configuration WHERE FFLM IS NOT NULL AND Radio_Name=@RN ORDER BY Date DESC) AS FFLM,
    (SELECT TOP 1 FFLT FROM Setting.Configuration WHERE FFLT IS NOT NULL AND Radio_Name=@RN ORDER BY Date DESC) AS FFLT
