DECLARE @RN CHAR(10);
SET @RN='{}';
SELECT
    (SELECT TOP 1 AIAI FROM Setting.Installation WHERE AIAI IS NOT NULL AND Radio_Name=@RN ORDER BY Date DESC) AS AIAI,
    (SELECT TOP 1 AIEL FROM Setting.Installation WHERE AIEL IS NOT NULL AND Radio_Name=@RN ORDER BY Date DESC) AS AIEL,
    (SELECT TOP 1 FFFE FROM Setting.Installation WHERE FFFE IS NOT NULL AND Radio_Name=@RN ORDER BY Date DESC) AS FFFE,
    (SELECT TOP 1 FFSC FROM Setting.Installation WHERE FFSC IS NOT NULL AND Radio_Name=@RN ORDER BY Date DESC) AS FFSC,
    (SELECT TOP 1 GRIN FROM Setting.Installation WHERE GRIN IS NOT NULL AND Radio_Name=@RN ORDER BY Date DESC) AS GRIN,
    (SELECT TOP 1 GRLO FROM Setting.Installation WHERE GRLO IS NOT NULL AND Radio_Name=@RN ORDER BY Date DESC) AS GRLO,
    (SELECT TOP 1 MSTY FROM Setting.Installation WHERE MSTY IS NOT NULL AND Radio_Name=@RN ORDER BY Date DESC) AS MSTY
