DECLARE @RN CHAR(10);
SET @RN='{}';
SELECT
    (SELECT TOP 1 GRDH FROM Setting.Network WHERE GRDH IS NOT NULL AND Radio_Name=@RN ORDER BY Date DESC) AS GRDH,
    (SELECT TOP 1 GRDN FROM Setting.Network WHERE GRDN IS NOT NULL AND Radio_Name=@RN ORDER BY Date DESC) AS GRDN,
    (SELECT TOP 1 GRIE FROM Setting.Network WHERE GRIE IS NOT NULL AND Radio_Name=@RN ORDER BY Date DESC) AS GRIE,
    (SELECT TOP 1 GRIV FROM Setting.Network WHERE GRIV IS NOT NULL AND Radio_Name=@RN ORDER BY Date DESC) AS GRIV,
    (SELECT TOP 1 GRNS FROM Setting.Network WHERE GRNS IS NOT NULL AND Radio_Name=@RN ORDER BY Date DESC) AS GRNS,
    (SELECT TOP 1 GRVE FROM Setting.Network WHERE GRVE IS NOT NULL AND Radio_Name=@RN ORDER BY Date DESC) AS GRVE
