DECLARE @RN CHAR(10);
SET @RN='{}';
SELECT
    (SELECT TOP 1 AIGA FROM Setting.RXConfiguration WHERE AIGA IS NOT NULL AND Radio_Name=@RN ORDER BY Date DESC) AS AIGA,
    (SELECT TOP 1 AITS FROM Setting.RXConfiguration WHERE AITS IS NOT NULL AND Radio_Name=@RN ORDER BY Date DESC) AS AITS,
    (SELECT TOP 1 FFCO FROM Setting.RXConfiguration WHERE FFCO IS NOT NULL AND Radio_Name=@RN ORDER BY Date DESC) AS FFCO,
    (SELECT TOP 1 FFSL FROM Setting.RXConfiguration WHERE FFSL IS NOT NULL AND Radio_Name=@RN ORDER BY Date DESC) AS FFSL,
    (SELECT TOP 1 GRBS FROM Setting.RXConfiguration WHERE GRBS IS NOT NULL AND Radio_Name=@RN ORDER BY Date DESC) AS GRBS,
    (SELECT TOP 1 GRIS FROM Setting.RXConfiguration WHERE GRIS IS NOT NULL AND Radio_Name=@RN ORDER BY Date DESC) AS GRIS,
    (SELECT TOP 1 RIRO FROM Setting.RXConfiguration WHERE RIRO IS NOT NULL AND Radio_Name=@RN ORDER BY Date DESC) AS RIRO
