DECLARE @RN CHAR(10);
SET @RN='{}';
SELECT
    (SELECT TOP 1 GRSE FROM Setting.SNMP WHERE GRSE IS NOT NULL AND Radio_Name=@RN ORDER BY Date DESC) AS GRSE,
    (SELECT TOP 1 GRSN FROM Setting.SNMP WHERE GRSN IS NOT NULL AND Radio_Name=@RN ORDER BY Date DESC) AS GRSN,
    (SELECT TOP 1 RUFL FROM Setting.SNMP WHERE RUFL IS NOT NULL AND Radio_Name=@RN ORDER BY Date DESC) AS RUFL,
    (SELECT TOP 1 RUFP FROM Setting.SNMP WHERE RUFP IS NOT NULL AND Radio_Name=@RN ORDER BY Date DESC) AS RUFP
