DECLARE @RN CHAR(10);
SET @RN='{}';
SELECT
    (SELECT TOP 1 ERBE FROM Setting.Status WHERE ERBE IS NOT NULL AND Radio_Name=@RN ORDER BY Date DESC) AS ERBE,
    (SELECT TOP 1 GRLR FROM Setting.Status WHERE GRLR IS NOT NULL AND Radio_Name=@RN ORDER BY Date DESC) AS GRLR,
    (SELECT TOP 1 GRLT FROM Setting.Status WHERE GRLT IS NOT NULL AND Radio_Name=@RN ORDER BY Date DESC) AS GRLT,
    (SELECT TOP 1 GRTI FROM Setting.Status WHERE GRTI IS NOT NULL AND Radio_Name=@RN ORDER BY Date DESC) AS GRTI,
    (SELECT TOP 1 RCLR FROM Setting.Status WHERE RCLR IS NOT NULL AND Radio_Name=@RN ORDER BY Date DESC) AS RCLR,
    (SELECT TOP 1 RCLV FROM Setting.Status WHERE RCLV IS NOT NULL AND Radio_Name=@RN ORDER BY Date DESC) AS RCLV
