DECLARE @RN CHAR(10);
SET @RN='{}';
SELECT
    (SELECT TOP 1 AITP FROM Event.SpecialSetting WHERE AITP IS NOT NULL AND Radio_Name=@RN ORDER BY Date DESC) AS AITP,
    (SELECT TOP 1 FFTO FROM Event.SpecialSetting WHERE FFTO IS NOT NULL AND Radio_Name=@RN ORDER BY Date DESC) AS FFTO,
    (SELECT TOP 1 RCIT FROM Event.SpecialSetting WHERE RCIT IS NOT NULL AND Radio_Name=@RN ORDER BY Date DESC) AS RCIT,
    (SELECT TOP 1 RCLP FROM Event.SpecialSetting WHERE RCLP IS NOT NULL AND Radio_Name=@RN ORDER BY Date DESC) AS RCLP,
    (SELECT TOP 1 RCNP FROM Event.SpecialSetting WHERE RCNP IS NOT NULL AND Radio_Name=@RN ORDER BY Date DESC) AS RCNP,
    (SELECT TOP 1 RCTS FROM Event.SpecialSetting WHERE RCTS IS NOT NULL AND Radio_Name=@RN ORDER BY Date DESC) AS RCTS