SELECT [RecordType]
      ,[CntConnect]
      ,[CntDisconnect]
      ,[CntIndicatorOn]
      ,[CntCBITWarning]
      ,[CntCBITError]
      ,[CntSentPacket]
      ,[CntKeepConnectionPacket]
      ,[CntReceivedPacket]
      ,[CntReceivedMessage]
      ,[CntReceivedCommandError]
      ,[CntReceivedAccessError]
      ,[CntReceivedTrapAnswer]
      ,[CntReceivedGetAnswer]
      ,[CntReceivedTrapAcknowledge]
      ,[CntReceivedSetAcknowledge]
      ,[CntQueryGenerated]
      ,[CntQueryExecuted]
      ,[CntCommandExecuted]
      ,[CntCommandRejected]
      ,[CntUpdateSettings]
      ,[CntUpdateSpecial]
      ,[CntUpdateTimer]
      ,[CntErrorPacketReceive]
      ,[CntErrorPacketEvaluation]
      ,[CntErrorPacketSending]
      ,[CntErrorConnection]
      ,[CntErrorQueryGeneration]
      ,[CntErrorQueryExecution]
      ,[CnrErrorCommandExecution]
      ,[CntErrorUpdateSettings]
      ,[CntErrorUpdateSpecial]
      ,[CntErrorUpdateTimer]
FROM Analyze.Counter
WHERE Radio_Name='{}';