USE RCMS;
GO

Insert Into Command.RadioInitial
    (RadioType, CKey, Request, Value, Active)
VALUES (0, 'SCPG', 'S', 60, 1),
       (0, 'AIAD', 'T', 1, 1),
       (0, 'AILA', 'T', 1, 1),
       (0, 'AISL', 'T', 1, 1),
       (0, 'ERGN', 'T', 1, 1),
       (0, 'EVEE', 'T', 1, 1),
       (0, 'FFMD', 'T', 1, 1),
       (0, 'FFRS', 'T', 1, 1),
       (0, 'FFSN', 'T', 1, 1),
       (0, 'FFSP', 'T', 1, 1),
       (0, 'FFSQ', 'T', 1, 1),
       (0, 'FFSR', 'T', 1, 1),
       (0, 'FFTR', 'T', 1, 1),
       (0, 'GRCS', 'T', 1, 1),
       (0, 'GRDS', 'T', 1, 1),
       (0, 'GRHN', 'T', 1, 1),
       (0, 'GRME', 'T', 1, 1),
       (0, 'GRNA', 'T', 1, 1),
       (0, 'GRTI', 'G', 1, 1),
       (0, 'GRUI', 'T', 1, 0),
       (0, 'GRUO', 'T', 1, 0),
       (0, 'MSAC', 'T', 1, 1),
       (0, 'RCLR', 'T', 1, 1),
       (0, 'RCMV', 'T', 1, 1),
       (0, 'RCPP', 'T', 1, 1),
       (0, 'RCRI', 'T', 1, 1),
       (0, 'RCTP', 'T', 1, 1),
       (0, 'RIRC', 'T', 1, 1),
       (0, 'SCSL', 'T', 1, 1),
       (0, 'SCSS', 'T', 1, 1),

	   (1, 'SCPG', 'S', 60, 1),
       (1, 'AIAD', 'T', 1, 1),
       (1, 'AILA', 'T', 1, 1),
       (1, 'AISL', 'T', 1, 1),
       (1, 'ERGN', 'T', 1, 1),
       (1, 'EVEE', 'T', 1, 1),
       (1, 'FFMD', 'T', 1, 1),
       (1, 'FFSP', 'T', 1, 1),
       (1, 'FFTR', 'T', 1, 1),
       (1, 'GRCS', 'T', 1, 1),
       (1, 'GRDS', 'T', 1, 1),
       (1, 'GRHN', 'T', 1, 1),
       (1, 'GRME', 'T', 1, 1),
       (1, 'GRNA', 'T', 1, 1),
       (1, 'GRTI', 'G', 1, 1),
       (1, 'GRUI', 'T', 1, 0),
       (1, 'GRUO', 'T', 1, 0),
       (1, 'MSAC', 'T', 1, 1),
       (1, 'RCLV', 'T', 1, 1),
       (1, 'RCMG', 'T', 1, 1),
       (1, 'RCMO', 'T', 1, 1),
       (1, 'RCMV', 'T', 1, 1),
       (1, 'RCPP', 'T', 1, 1),
       (1, 'RCTC', 'T', 1, 1),
       (1, 'RCTO', 'T', 1, 1),
       (1, 'RCTP', 'T', 1, 1),
       (1, 'RCTV', 'T', 1, 1),
       (1, 'RCTW', 'T', 1, 1),
       (1, 'RCVV', 'T', 1, 1),
       (1, 'SCSL', 'T', 1, 1),
       (1, 'SCSS', 'T', 1, 1);
GO

INSERT INTO RCMS.Command.KeyInformation (CKey, TX_Name, RX_Name, Parameter_Type, Parameter_Unit, INT_Parameter_Min,
                                         INT_Parameter_Max, INT_Parameter_Step, FLOAT_Parameter_Min,
                                         FLOAT_Parameter_Max, FLOAT_Parameter_Step, STRING_Max_Length, Convertor_Table,
                                         RegisterTable, TX_Support, RX_Support, GET_Support, SET_Support, TRAP_Support,
                                         GET_Need_Value, Update_Need_Restart, Work_As_Expected, Fully_Identified)
VALUES (N'ACBC', null, null, N'INT', null, null, null, null, null, null, null, null, null, null, 1, 1, 1, 1, 0, 0, 0, 1,
        0),
       (N'ACBF', null, null, N'*', null, null, null, null, null, null, null, null, null, null, 1, 1, 0, 1, 0, 0, 0, 1,
        0),
       (N'ACBS', null, null, N'INT', null, null, null, null, null, null, null, null, null, null, 1, 1, 1, 1, 0, 0, 0, 1,
        0),
       (N'ACDF', null, null, N'*', null, null, null, null, null, null, null, null, null, null, 1, 1, 0, 1, 0, 0, 0, 1,
        0),
       (N'ACMC', null, null, N'*', null, null, null, null, null, null, null, null, null, null, 0, 1, 1, 0, 0, 0, 0, 1,
        0),
       (N'ACPL', null, null, N'INT', null, null, null, null, null, null, null, null, null, null, 1, 1, 1, 1, 0, 0, 0, 1,
        0),
       (N'ACRC', null, null, N'*', null, null, null, null, null, null, null, null, null, null, 1, 1, 1, 0, 0, 0, 0, 1,
        0),
       (N'ACST', null, null, N'*', null, null, null, null, null, null, null, null, null, null, 0, 1, 1, 0, 0, 0, 0, 1,
        0),
       (N'ACTE', null, null, N'INT', null, null, null, null, null, null, null, null, null, null, 1, 1, 1, 1, 0, 0, 0, 1,
        0),
       (N'ACTF', null, null, N'INT', null, null, null, null, null, null, null, null, null, null, 1, 1, 1, 1, 0, 0, 0, 1,
        0);
GO

INSERT INTO RCMS.Command.KeyInformation (CKey, TX_Name, RX_Name, Parameter_Type, Parameter_Unit, INT_Parameter_Min,
                                         INT_Parameter_Max, INT_Parameter_Step, FLOAT_Parameter_Min,
                                         FLOAT_Parameter_Max, FLOAT_Parameter_Step, STRING_Max_Length, Convertor_Table,
                                         RegisterTable, TX_Support, RX_Support, GET_Support, SET_Support, TRAP_Support,
                                         GET_Need_Value, Update_Need_Restart, Work_As_Expected, Fully_Identified)
VALUES (N'ACTI', null, null, N'INT', null, null, null, null, null, null, null, null, null, null, 1, 1, 1, 1, 0, 0, 0, 1,
        0),
       (N'ACUF', null, null, N'*', null, null, null, null, null, null, null, null, null, null, 1, 1, 0, 1, 0, 0, 0, 1,
        0),
       (N'AIAD', N'Audio Delay', N'Audio Delay', N'INT', N'ms', 0, 250, 1, null, null, null, null, null,
        N'Event.ERadio', 1, 1, 1, 1, 1, 0, 0, 1, 1),
       (N'AIAI', N'Select Audio Interface', N'Select Audio Interface', N'INT', null, null, null, null, null, null, null,
        null, N'Common.AudioInterface', N'Setting.SRadio', 1, 1, 1, 1, 0, 0, 1, 1, 1),
       (N'AICA', N'Tx Audio ALC', null, N'INT', null, null, null, null, null, null, null, null, N'Common.EnableDisable',
        N'Setting.SRadio', 1, 0, 1, 1, 0, 0, 1, 1, 1),
       (N'AICE', null, null, N'*', null, null, null, null, null, null, null, null, null, null, 1, 1, 0, 1, 0, 0, 0, 1,
        0),
       (N'AICV', null, null, N'*', null, null, null, null, null, null, null, null, null, null, 1, 1, 0, 1, 0, 0, 0, 1,
        0),
       (N'AIEL', N'Line Interface in local mode', N'Line Interface in local mode', N'INT', null, null, null, null, null,
        null, null, null, N'Common.EnableDisable', N'Setting.SRadio', 1, 1, 1, 1, 0, 0, 1, 1, 1),
       (N'AIGA', null, N'Rx Audio AGC', N'INT', null, null, null, null, null, null, null, null, N'Common.EnableDisable',
        N'Setting.SRadio', 0, 1, 1, 1, 0, 0, 1, 1, 1),
       (N'AIGE', null, null, N'*', null, null, null, null, null, null, null, null, null, null, 1, 1, 0, 1, 0, 0, 0, 1,
        0);
GO
INSERT INTO RCMS.Command.KeyInformation (CKey, TX_Name, RX_Name, Parameter_Type, Parameter_Unit, INT_Parameter_Min,
                                         INT_Parameter_Max, INT_Parameter_Step, FLOAT_Parameter_Min,
                                         FLOAT_Parameter_Max, FLOAT_Parameter_Step, STRING_Max_Length, Convertor_Table,
                                         RegisterTable, TX_Support, RX_Support, GET_Support, SET_Support, TRAP_Support,
                                         GET_Need_Value, Update_Need_Restart, Work_As_Expected, Fully_Identified)
VALUES (N'AIGV', null, null, N'*', null, null, null, null, null, null, null, null, null, null, 1, 1, 0, 1, 0, 0, 0, 1,
        0),
       (N'AIIW', null, null, N'*', null, null, null, null, null, null, null, null, null, null, 1, 1, 0, 1, 0, 0, 0, 1,
        0),
       (N'AILA', N'TX Audio Level', N'RX Audio Level', N'INT', N'dBm', -30, 10, 1, null, null, null, null, null,
        N'Event.ERadio', 1, 1, 1, 1, 1, 0, 0, 1, 1),
       (N'AILE', null, null, N'*', null, null, null, null, null, null, null, null, null, null, 1, 1, 0, 1, 0, 0, 0, 1,
        0),
       (N'AILV', null, null, N'*', null, null, null, null, null, null, null, null, null, null, 1, 1, 0, 1, 0, 0, 0, 1,
        0),
       (N'AIML', N'Mute Loudspeaker', null, N'INT', null, null, null, null, null, null, null, null,
        N'Common.EnableDisable', N'Setting.SRadio', 1, 0, 1, 1, 0, 0, 1, 1, 1),
       (N'AISE', N'PTT Signaling', N'SQ-RSSI Signaling', N'INT', null, null, null, null, null, null, null, null,
        N'Common.EnableDisable', N'Setting.SRadio', 1, 1, 1, 1, 0, 0, 1, 1, 1),
       (N'AISF', N'PTT Signaling Frequency', N'SQ Signaling Frequency', N'INT', null, null, null, null, null, null,
        null, null, null, N'Setting.SRadio', 1, 1, 1, 1, 0, 0, 1, 1, 1),
       (N'AISL', N'PTT Signaling Threshold', N'SQ-RSSI Signaling Level', N'INT', null, null, null, null, null, null,
        null, null, null, N'Event.ERadio', 1, 1, 1, 1, 1, 0, 0, 1, 1),
       (N'AITP', N'Tx Pre-Emphasis', null, N'INT', N'dBm', 0, 15, 1, null, null, null, null, null,
        N'Setting.SRadio', 1, 0, 1, 1, 0, 0, 0, 1, 1);
GO
INSERT INTO RCMS.Command.KeyInformation (CKey, TX_Name, RX_Name, Parameter_Type, Parameter_Unit, INT_Parameter_Min,
                                         INT_Parameter_Max, INT_Parameter_Step, FLOAT_Parameter_Min,
                                         FLOAT_Parameter_Max, FLOAT_Parameter_Step, STRING_Max_Length, Convertor_Table,
                                         RegisterTable, TX_Support, RX_Support, GET_Support, SET_Support, TRAP_Support,
                                         GET_Need_Value, Update_Need_Restart, Work_As_Expected, Fully_Identified)
VALUES (N'AITS', null, N'True Side-tone Transceiver', N'INT', null, null, null, null, null, null, null, null,
        N'Common.EnableDisable', N'Setting.SRadio', 0, 1, 1, 1, 0, 0, 1, 1, 1),
       (N'AIWL', null, null, N'*', null, null, null, null, null, null, null, null, null, null, 0, 1, 0, 1, 1, 0, 0, 1,
        0),
       (N'BMEB', null, null, N'*', null, null, null, null, null, null, null, null, null, null, 1, 1, 0, 1, 0, 0, 0, 1,
        0),
       (N'ERBE', N'Boot Error List', N'Boot Error List', N'INT', null, null, null, null, null, null, null, null, null,
        N'Setting.SRadio', 1, 1, 1, 0, 0, 0, 0, 1, 1),
       (N'ERGN', N'GO-NOGO Status', N'GO-NOGO Status', N'INT', null, null, null, null, null, null, null, null,
        N'Common.Operation', N'Event.ERadio', 1, 1, 1, 0, 1, 0, 0, 1, 1),
       (N'EVAC', null, null, N'*', null, null, null, null, null, null, null, null, null, null, 1, 1, 0, 1, 0, 0, 0, 1,
        0),
       (N'EVCL', N'Clear Event List', N'Clear Event List', N'*', null, null, null, null, null, null, null, null, null,
        N'Event.ERadio', 1, 1, 0, 1, 0, 0, 0, 1, 1),
       (N'EVEE', N'Read Event Entry', N'Read Event Entry', N'*', null, null, null, null, null, null, null, null, null,
        N'Event.EventList', 1, 1, 0, 0, 1, 0, 0, 1, 1),
       (N'EVEL', N'Event Log List', N'Event Log List', N'*', null, null, null, null, null, null, null, null, null,
        N'Event.EventList', 1, 1, 1, 0, 0, 0, 0, 1, 1),
       (N'EVSR', N'Read Sequence Number Page', N'Read Sequence Number Page', N'*', null, null, null, null, null, null,
        null, null, null, N'Setting.SRadio', 1, 1, 1, 0, 0, 0, 0, 1, 1);
GO
INSERT INTO RCMS.Command.KeyInformation (CKey, TX_Name, RX_Name, Parameter_Type, Parameter_Unit, INT_Parameter_Min,
                                         INT_Parameter_Max, INT_Parameter_Step, FLOAT_Parameter_Min,
                                         FLOAT_Parameter_Max, FLOAT_Parameter_Step, STRING_Max_Length, Convertor_Table,
                                         RegisterTable, TX_Support, RX_Support, GET_Support, SET_Support, TRAP_Support,
                                         GET_Need_Value, Update_Need_Restart, Work_As_Expected, Fully_Identified)
VALUES (N'FFBI', null, null, N'*', null, null, null, null, null, null, null, null, null, null, 1, 1, 1, 0, 0, 0, 0, 1,
        0),
       (N'FFBL', N'Frequency Blocking Ranges', N'Frequency Blocking Ranges', N'*', null, null, null, null, null, null,
        null, null, null, N'Setting.SRadio', 1, 1, 1, 1, 0, 0, 1, 1, 1),
       (N'FFCO', null, N'Carrier Override', N'INT', null, null, null, null, null, null, null, null,
        N'Common.EnableDisable', N'Setting.SRadio', 0, 1, 1, 1, 0, 0, 1, 1, 1),
       (N'FFEA', N'ACARS Data Mode', N'ACARS Data Mode', N'INT', null, null, null, null, null, null, null, null,
        N'Common.EnableDisable', N'Setting.SRadio', 1, 1, 1, 1, 0, 0, 1, 1, 1),
       (N'FFEC', null, null, N'*', null, null, null, null, null, null, null, null, null, null, 1, 1, 0, 1, 0, 0, 0, 1,
        0),
       (N'FFEW', null, null, N'*', null, null, null, null, null, null, null, null, null, null, 1, 1, 0, 1, 0, 0, 0, 1,
        0),
       (N'FFFC', N'Filter Configuration', N'Filter Configuration', N'*', null, null, null, null, null, null, null, null,
        null, N'Setting.SRadio', 1, 1, 1, 0, 0, 0, 0, 1, 1),
       (N'FFFE', N'Motor Tuned Telsa Filter', N'Motor Tuned Telsa Filter', N'INT', null, null, null, null, null, null,
        null, null, N'Common.EnableDisable', N'Setting.SRadio', 1, 1, 1, 1, 0, 0, 1, 1, 1),
       (N'FFLM', N'Local Mode', N'Local Mode', N'INT', null, null, null, null, null, null, null, null,
        N'Common.EnableDisable', N'Setting.SRadio', 1, 1, 1, 1, 0, 0, 1, 1, 1),
       (N'FFLT', N'Local Mode Timeout', N'Local Mode Timeout', N'INT', N'Second', 60, 900, 1, null, null, null, null,
        null, N'Setting.SRadio', 1, 1, 1, 1, 0, 0, 1, 1, 1);
GO
INSERT INTO RCMS.Command.KeyInformation (CKey, TX_Name, RX_Name, Parameter_Type, Parameter_Unit, INT_Parameter_Min,
                                         INT_Parameter_Max, INT_Parameter_Step, FLOAT_Parameter_Min,
                                         FLOAT_Parameter_Max, FLOAT_Parameter_Step, STRING_Max_Length, Convertor_Table,
                                         RegisterTable, TX_Support, RX_Support, GET_Support, SET_Support, TRAP_Support,
                                         GET_Need_Value, Update_Need_Restart, Work_As_Expected, Fully_Identified)
VALUES (N'FFMD', N'Modulation Mode', N'Modulation Mode', N'INT', null, null, null, null, null, null, null, null,
        N'Common.ModulationMode', N'Event.ERadio', 1, 1, 1, 1, 1, 0, 0, 1, 1),
       (N'FFRS', null, N'RSSI', N'INT', null, null, null, null, null, null, null, null, null, N'Event.Reception', 0, 1,
        1, 0, 1, 0, 0, 1, 1),
       (N'FFSC', N'Single Channel', N'Single Channel', N'INT', null, null, null, null, null, null, null, null,
        N'Common.EnableDisable', N'Setting.SRadio', 1, 1, 1, 1, 0, 0, 1, 1, 1),
       (N'FFSL', null, N'SNR-RSSI SQ Logic Operation', N'INT', null, null, null, null, null, null, null, null,
        N'Common.SQLogic', N'Setting.SRadio', 0, 1, 1, 1, 0, 0, 1, 1, 1),
       (N'FFSN', null, N'SNR Squelch Threshold', N'INT', N'dB', 6, 20, 1, null, null, null, null, null, N'Event.ERadio',
        0, 1, 1, 1, 1, 0, 0, 1, 1),
       (N'FFSP', N'Channel Spacing', N'Channel Spacing', N'INT', null, null, null, null, null, null, null, null,
        N'Common.ChannelSpacing', N'Event.ERadio', 1, 1, 1, 1, 1, 0, 0, 1, 1),
       (N'FFSQ', null, N'SQ Circuit', N'INT', null, null, null, null, null, null, null, null, N'Common.OnOff',
        N'Event.ERadio', 0, 1, 1, 1, 1, 0, 0, 1, 1),
       (N'FFSR', null, N'RSSI Squelch Threshold', N'INT', N'uV', 1, 50, 1, null, null, null, null, null,
        N'Event.ERadio', 0, 1, 1, 1, 1, 0, 0, 1, 1),
       (N'FFTO', N'Carrier Offset', null, N'INT', null, 0, 13, 1, null, null, null, null, N'Common.TXOffset',
        N'Setting.SRadio', 1, 0, 1, 1, 0, 0, 0, 1, 1),
       (N'FFTR', N'Frequency', N'Frequency', N'INT', N'Hz', 118000000, 136975000, 25000, null, null, null, null, null,
        N'Event.ERadio', 1, 1, 1, 1, 1, 0, 0, 1, 1);
GO
INSERT INTO RCMS.Command.KeyInformation (CKey, TX_Name, RX_Name, Parameter_Type, Parameter_Unit, INT_Parameter_Min,
                                         INT_Parameter_Max, INT_Parameter_Step, FLOAT_Parameter_Min,
                                         FLOAT_Parameter_Max, FLOAT_Parameter_Step, STRING_Max_Length, Convertor_Table,
                                         RegisterTable, TX_Support, RX_Support, GET_Support, SET_Support, TRAP_Support,
                                         GET_Need_Value, Update_Need_Restart, Work_As_Expected, Fully_Identified)
VALUES (N'GRAC', N'ACL (Access Control List)', N'ACL (Access Control List)', N'*', null, null, null, null, null, null,
        null, null, null, N'Setting.Access', 1, 1, 1, 1, 0, 0, 1, 1, 1),
       (N'GRAD', null, null, N'*', null, null, null, null, null, null, null, null, null, null, 1, 1, 0, 1, 0, 0, 0, 1,
        0),
       (N'GRAP', null, null, N'*', null, null, null, null, null, null, null, null, null, null, 1, 1, 1, 1, 0, 0, 0, 1,
        0),
       (N'GRAS', N'ATR Switch Mode', null, N'INT', null, null, null, null, null, null, null, null, N'Common.ATRMode',
        N'Setting.SRadio', 1, 0, 1, 1, 0, 0, 1, 1, 1),
       (N'GRAT', N'All Trap OFF', N'All Trap OFF', N'*', null, null, null, null, null, null, null, null, null,
        N'Event.ERadio', 1, 1, 0, 1, 0, 0, 0, 1, 1),
       (N'GRBS', null, N'Best Signal Selection', N'INT', null, null, null, null, null, null, null, null,
        N'Common.EnableDisable', N'Setting.SRadio', 0, 1, 1, 1, 0, 0, 1, 1, 1),
       (N'GRCB', null, null, N'INT', null, null, null, null, null, null, null, null, null, null, 0, 1, 1, 1, 0, 0, 0, 1,
        0),
       (N'GRCO', N'5 Carrier Offset', null, N'INT', null, null, null, null, null, null, null, null,
        N'Common.EnableDisable', N'Setting.SRadio', 1, 0, 1, 1, 0, 0, 1, 1, 1),
       (N'GRCP', null, null, N'*', null, null, null, null, null, null, null, null, null, null, 1, 1, 0, 1, 0, 0, 0, 1,
        0),
       (N'GRCS', N'CBIT Status', N'CBIT Status', N'INT', null, null, null, null, null, null, null, null, null,
        N'Event.ECBIT', 1, 1, 1, 0, 1, 0, 0, 1, 1);
GO
INSERT INTO RCMS.Command.KeyInformation (CKey, TX_Name, RX_Name, Parameter_Type, Parameter_Unit, INT_Parameter_Min,
                                         INT_Parameter_Max, INT_Parameter_Step, FLOAT_Parameter_Min,
                                         FLOAT_Parameter_Max, FLOAT_Parameter_Step, STRING_Max_Length, Convertor_Table,
                                         RegisterTable, TX_Support, RX_Support, GET_Support, SET_Support, TRAP_Support,
                                         GET_Need_Value, Update_Need_Restart, Work_As_Expected, Fully_Identified)
VALUES (N'GRCU', null, null, N'FLOAT', null, null, null, null, null, null, null, null, null, null, 0, 1, 1, 0, 0, 0, 0,
        1, 0),
       (N'GRDH', N'DHCP Enabled', N'DHCP Enabled', N'INT', null, null, null, null, null, null, null, null,
        N'Common.EnableDisable', N'Setting.SRadio', 1, 1, 1, 1, 0, 0, 1, 1, 1),
       (N'GRDN', N'Primary and Secondary DNS', N'Primary and Secondary DNS', N'*', null, null, null, null, null, null,
        null, null, null, N'Setting.SRadio', 1, 1, 1, 1, 0, 0, 1, 1, 1),
       (N'GRDS', N'Device Status', N'Device Status', N'*', null, null, null, null, null, null, null, null, null,
        N'Event.Status', 1, 1, 1, 0, 1, 0, 0, 1, 1),
       (N'GREX', N'External Amplifier', null, N'INT', null, null, null, null, null, null, null, null,
        N'Common.EnableDisable', N'Setting.SRadio', 1, 0, 1, 1, 0, 0, 1, 1, 1),
       (N'GRHN', N'Hostname', N'Hostname', N'*', null, null, null, null, null, null, null, 24, null, N'Event.ERadio', 1,
        1, 1, 1, 1, 0, 0, 1, 1),
       (N'GRIE', N'Second IP Address Enabled', N'Second IP Address Enabled', N'INT', null, null, null, null, null, null,
        null, null, N'Common.EnableDisable', N'Setting.SRadio', 1, 1, 1, 1, 0, 0, 1, 1, 1),
       (N'GRII', N'Second IP Address', N'Second IP Address', N'*', null, null, null, null, null, null, null, null, null,
        N'Setting.IP', 1, 1, 1, 1, 1, 0, 1, 1, 1),
       (N'GRIL', N'Inventory List', N'Inventory List', N'*', null, null, null, null, null, null, null, null, null,
        N'Setting.Inventory', 1, 1, 1, 0, 0, 1, 0, 1, 1),
       (N'GRIN', N'Installation Info', N'Installation Info', N'*', null, null, null, null, null, null, null, 20, null,
        N'Setting.SRadio', 1, 1, 1, 1, 0, 0, 1, 1, 1);
GO
INSERT INTO RCMS.Command.KeyInformation (CKey, TX_Name, RX_Name, Parameter_Type, Parameter_Unit, INT_Parameter_Min,
                                         INT_Parameter_Max, INT_Parameter_Step, FLOAT_Parameter_Min,
                                         FLOAT_Parameter_Max, FLOAT_Parameter_Step, STRING_Max_Length, Convertor_Table,
                                         RegisterTable, TX_Support, RX_Support, GET_Support, SET_Support, TRAP_Support,
                                         GET_Need_Value, Update_Need_Restart, Work_As_Expected, Fully_Identified)
VALUES (N'GRIP', N'IP Address', N'IP Address', N'*', null, null, null, null, null, null, null, null, null,
        N'Setting.IP', 1, 1, 1, 1, 1, 0, 1, 1, 1),
       (N'GRIS', null, N'Rx Input Sensitivity', N'INT', null, null, null, null, null, null, null, null,
        N'Common.RXSensitivity', N'Setting.SRadio', 0, 1, 1, 1, 0, 0, 1, 1, 1),
       (N'GRIV', N'IPv6 Enabled', N'IPv6 Enabled', N'INT', null, null, null, null, null, null, null, null,
        N'Common.EnableDisable', N'Setting.SRadio', 1, 1, 1, 1, 0, 0, 1, 1, 1),
       (N'GRKD', null, null, N'INT', null, null, null, null, null, null, null, null, null, null, 1, 1, 1, 1, 0, 0, 0, 1,
        0),
       (N'GRKU', null, null, N'INT', null, null, null, null, null, null, null, null, null, null, 1, 1, 1, 1, 0, 0, 0, 1,
        0),
       (N'GRLO', N'Location Info', N'Location Info', N'*', null, null, null, null, null, null, null, 20, null,
        N'Setting.SRadio', 1, 1, 1, 1, 0, 0, 1, 1, 1),
       (N'GRLR', null, N'Measure RX Audio Level', N'INT', null, null, null, null, null, null, null, null, null,
        N'Setting.SRadio', 0, 1, 1, 0, 0, 0, 0, 1, 1),
       (N'GRLT', N'Measure TX Audio Level', null, N'INT', null, null, null, null, null, null, null, null, null,
        N'Setting.SRadio', 1, 0, 1, 0, 0, 0, 0, 1, 1),
       (N'GRME', N'Last Maintenance TimeStamp', N'Last Maintenance TimeStamp', N'INT', null, null, null, null, null,
        null, null, null, N'Timestamp', N'Event.ERadio', 1, 1, 1, 1, 1, 0, 0, 1, 1),
       (N'GRNA', N'NTP Sync Active', N'NTP Sync Active', N'INT', null, null, null, null, null, null, null, null,
        N'Common.Activation', N'Event.ERadio', 1, 1, 1, 0, 1, 0, 0, 1, 1);
GO
INSERT INTO RCMS.Command.KeyInformation (CKey, TX_Name, RX_Name, Parameter_Type, Parameter_Unit, INT_Parameter_Min,
                                         INT_Parameter_Max, INT_Parameter_Step, FLOAT_Parameter_Min,
                                         FLOAT_Parameter_Max, FLOAT_Parameter_Step, STRING_Max_Length, Convertor_Table,
                                         RegisterTable, TX_Support, RX_Support, GET_Support, SET_Support, TRAP_Support,
                                         GET_Need_Value, Update_Need_Restart, Work_As_Expected, Fully_Identified)
VALUES (N'GRNC', N'CBIT Items with Configurability', N'CBIT Items with Configurability', N'*', null, null, null, null,
        null, null, null, null, null, N'Setting.SCBIT,Common.CBITList', 1, 1, 1, 1, 0, 0, 1, 1, 1),
       (N'GRND', N'Inventory Item', N'Inventory Item', N'*', null, null, null, null, null, null, null, null, null,
        N'Setting.Inventory', 1, 1, 1, 0, 0, 1, 0, 1, 1),
       (N'GRNS', N'NTP Server', N'NTP Server', N'*', null, null, null, null, null, null, null, null, null,
        N'Setting.SRadio', 1, 1, 1, 1, 1, 0, 1, 1, 1),
       (N'GRRI', null, null, N'INT', null, null, null, null, null, null, null, null, null, null, 1, 1, 1, 1, 0, 0, 0, 1,
        0),
       (N'GRRO', null, null, N'*', null, null, null, null, null, null, null, null, null, null, 1, 1, 0, 1, 0, 0, 0, 1,
        0),
       (N'GRSE', N'SNMP Enable', N'SNMP Enable', N'INT', null, null, null, null, null, null, null, null,
        N'Common.EnableDisable', N'Setting.SRadio', 1, 1, 1, 1, 0, 0, 1, 1, 1),
       (N'GRSN', N'SNMP Community String', N'SNMP Community String', N'*', null, null, null, null, null, null, null,
        null, null, N'Setting.SRadio', 1, 1, 1, 1, 0, 0, 1, 1, 1),
       (N'GRSV', N'Software Versions', N'Software Versions', N'*', null, null, null, null, null, null, null, null, null,
        N'Setting.Software', 1, 1, 1, 0, 0, 0, 0, 1, 1),
       (N'GRTI', N'RTC Time and Date', N'RTC Time and Date', N'*', null, null, null, null, null, null, null, null, null,
        N'Event.ERadio', 1, 1, 1, 0, 1, 0, 0, 1, 1),
       (N'GRUI', N'User Input', N'User Input', N'INT', null, null, null, null, null, null, null, null, null,
        N'Event.ERadio', 1, 1, 1, 0, 1, 0, 0, 1, 1);
GO
INSERT INTO RCMS.Command.KeyInformation (CKey, TX_Name, RX_Name, Parameter_Type, Parameter_Unit, INT_Parameter_Min,
                                         INT_Parameter_Max, INT_Parameter_Step, FLOAT_Parameter_Min,
                                         FLOAT_Parameter_Max, FLOAT_Parameter_Step, STRING_Max_Length, Convertor_Table,
                                         RegisterTable, TX_Support, RX_Support, GET_Support, SET_Support, TRAP_Support,
                                         GET_Need_Value, Update_Need_Restart, Work_As_Expected, Fully_Identified)
VALUES (N'GRUO', N'User Output', N'User Output', N'*', null, null, null, null, null, null, null, null, null,
        N'Event.ERadio', 1, 1, 1, 0, 1, 0, 0, 0, 0),
       (N'GRVE', N'GB2PP Version', N'GB2PP Version', N'FLOAT', null, null, null, null, null, null, null, null, null,
        N'Setting.SRadio', 1, 1, 1, 0, 0, 0, 0, 1, 1),
       (N'LBPT', null, null, N'INT', null, null, null, null, null, null, null, null, null, null, 1, 1, 1, 1, 0, 0, 0, 1,
        0),
       (N'LBRT', null, null, N'INT', null, null, null, null, null, null, null, null, null, null, 1, 1, 1, 1, 0, 0, 0, 1,
        0),
       (N'LBSR', null, null, N'*', null, null, null, null, null, null, null, null, null, null, 1, 1, 1, 0, 0, 0, 0, 1,
        0),
       (N'MSAC', N'Activation Status', N'Activation Status', N'INT', null, null, null, null, null, null, null, null,
        N'Common.Activation', N'Event.ERadio', 1, 1, 1, 1, 1, 0, 0, 1, 1),
       (N'MSGO', N'Skip to GO', N'Skip to GO', N'*', null, null, null, null, null, null, null, null, null,
        N'Event.ERadio', 1, 1, 0, 1, 0, 0, 0, 1, 1),
       (N'MSTY', N'Main-Standby Type', N'Main-Standby Type', N'INT', null, null, null, null, null, null, null, null,
        N'Common.MainStandby', N'Setting.SRadio', 1, 1, 1, 1, 0, 0, 1, 1, 1),
       (N'NMBQ', null, null, N'*', null, null, null, null, null, null, null, null, null, null, 1, 1, 0, 1, 0, 0, 0, 1,
        0),
       (N'NMSL', null, null, N'*', null, null, null, null, null, null, null, null, null, null, 1, 1, 0, 1, 0, 0, 0, 1,
        0);
GO
INSERT INTO RCMS.Command.KeyInformation (CKey, TX_Name, RX_Name, Parameter_Type, Parameter_Unit, INT_Parameter_Min,
                                         INT_Parameter_Max, INT_Parameter_Step, FLOAT_Parameter_Min,
                                         FLOAT_Parameter_Max, FLOAT_Parameter_Step, STRING_Max_Length, Convertor_Table,
                                         RegisterTable, TX_Support, RX_Support, GET_Support, SET_Support, TRAP_Support,
                                         GET_Need_Value, Update_Need_Restart, Work_As_Expected, Fully_Identified)
VALUES (N'OPOL', null, null, N'INT', null, null, null, null, null, null, null, null, null, null, 1, 1, 1, 0, 0, 0, 0, 1,
        0),
       (N'PTDC', null, null, N'INT', null, null, null, null, null, null, null, null, null, null, 1, 1, 1, 0, 0, 0, 0, 1,
        0),
       (N'PTDE', null, null, N'INT', null, null, null, null, null, null, null, null, null, null, 1, 1, 1, 1, 0, 0, 0, 1,
        0),
       (N'PTDT', null, null, N'INT', null, null, null, null, null, null, null, null, null, null, 1, 1, 1, 1, 0, 0, 0, 1,
        0),
       (N'PTUC', null, null, N'INT', null, null, null, null, null, null, null, null, null, null, 1, 1, 1, 0, 0, 0, 0, 1,
        0),
       (N'PTUE', null, null, N'INT', null, null, null, null, null, null, null, null, null, null, 1, 1, 1, 1, 0, 0, 0, 1,
        0),
       (N'PTUT', null, null, N'INT', null, null, null, null, null, null, null, null, null, null, 1, 1, 1, 1, 0, 0, 0, 1,
        0),
       (N'RCDP', N'PTT Timeout', null, N'*', N'Second', null, null, null, null, null, null, null, null,
        N'Setting.SRadio', 1, 0, 1, 1, 0, 0, 1, 1, 1),
       (N'RCIT', N'TX Inhibition', null, N'INT', null, 0, 1, 1, null, null, null, null, N'Common.Inhibit',
        N'Setting.SRadio', 1, 0, 1, 1, 0, 0, 0, 1, 1),
       (N'RCLP', N'Tx Low Power Level', null, N'INT', N'Watt', 5, 20, 1, null, null, null, null, null,
        N'Setting.SRadio', 1, 0, 1, 1, 0, 0, 0, 1, 1);
GO
INSERT INTO RCMS.Command.KeyInformation (CKey, TX_Name, RX_Name, Parameter_Type, Parameter_Unit, INT_Parameter_Min,
                                         INT_Parameter_Max, INT_Parameter_Step, FLOAT_Parameter_Min,
                                         FLOAT_Parameter_Max, FLOAT_Parameter_Step, STRING_Max_Length, Convertor_Table,
                                         RegisterTable, TX_Support, RX_Support, GET_Support, SET_Support, TRAP_Support,
                                         GET_Need_Value, Update_Need_Restart, Work_As_Expected, Fully_Identified)
VALUES (N'RCLR', null, N'Last RSSI Value', N'INT', null, null, null, null, null, null, null, null, null,
        N'Event.ERadio', 0, 1, 1, 0, 1, 0, 0, 1, 1),
       (N'RCLV', N'Last VSWR Value', null, N'FLOAT', null, null, null, null, null, null, null, null, null,
        N'Event.ERadio', 1, 0, 1, 0, 1, 0, 0, 1, 1),
       (N'RCMG', N'TX Modulation Depth', null, N'INT', N'%', 30, 90, 1, null, null, null, null, null, N'Event.ERadio',
        1, 0, 1, 1, 1, 0, 0, 1, 1),
       (N'RCMO', N'Measuring Modulation Depth', null, N'INT', null, null, null, null, null, null, null, null, null,
        N'Event.Transmission', 1, 0, 1, 0, 1, 0, 0, 1, 1),
       (N'RCMV', N'DC Voltages', N'DC Voltages', N'*', null, null, null, null, null, null, null, null, null,
        N'Event.Reception,Event.Transmission', 1, 1, 1, 0, 1, 0, 0, 1, 1),
       (N'RCNP', N'TX Normal Power Level', null, N'INT', N'Watt', 5, 50, 1, null, null, null, null, null,
        N'Setting.SRadio', 1, 0, 1, 1, 0, 0, 0, 1, 1),
       (N'RCOC', N'Operating Hours Counter', N'Operating Hours Counter', N'INT', N'Hour', null, null, null, null, null,
        null, null, null, N'Common.Radio', 1, 1, 1, 0, 0, 0, 0, 1, 1),
       (N'RCPF', N'Press Command Without Tone', N'Press Command Without Tone', N'*', null, null, null, null, null, null,
        null, null, null, N'Event.ERadio', 1, 0, 0, 1, 0, 0, 0, 1, 1),
       (N'RCPP', N'Preset Page Number', N'Preset Page Number', N'INT', null, null, null, null, null, null, null, null,
        null, N'Event.ERadio', 1, 1, 1, 1, 1, 0, 0, 1, 1),
       (N'RCPT', N'Press Command With Tone', N'Press Command With Tone', N'*', null, null, null, null, null, null, null,
        null, null, N'Event.ERadio', 1, 0, 0, 1, 0, 0, 0, 1, 1);
GO
INSERT INTO RCMS.Command.KeyInformation (CKey, TX_Name, RX_Name, Parameter_Type, Parameter_Unit, INT_Parameter_Min,
                                         INT_Parameter_Max, INT_Parameter_Step, FLOAT_Parameter_Min,
                                         FLOAT_Parameter_Max, FLOAT_Parameter_Step, STRING_Max_Length, Convertor_Table,
                                         RegisterTable, TX_Support, RX_Support, GET_Support, SET_Support, TRAP_Support,
                                         GET_Need_Value, Update_Need_Restart, Work_As_Expected, Fully_Identified)
VALUES (N'RCPV', N'Preset Page', N'Preset Page', N'*', null, null, null, null, null, null, null, null, null, null, 1, 1,
        1, 1, 0, 0, 1, 1, 1),
       (N'RCRI', null, N'SQ Indicator', N'INT', null, null, null, null, null, null, null, null, null,
        N'Event.Reception', 0, 1, 1, 0, 1, 0, 0, 1, 1),
       (N'RCRR', N'Restart Radio', N'Restart Radio', N'*', null, null, null, null, null, null, null, null, null,
        N'Event.ERadio', 1, 1, 0, 1, 0, 0, 0, 1, 1),
       (N'RCTC', N'PTT Indicator', null, N'INT', null, null, null, null, null, null, null, null, null,
        N'Event.Transmission', 1, 0, 1, 0, 1, 0, 0, 1, 1),
       (N'RCTO', N'Measure TX Power', null, N'INT', null, null, null, null, null, null, null, null, null,
        N'Event.Transmission', 1, 0, 1, 0, 1, 0, 0, 1, 1),
       (N'RCTP', N'Temperatures', N'Temperatures', N'*', null, null, null, null, null, null, null, null, null,
        N'Event.Reception,Event.Transmission', 1, 1, 1, 0, 1, 0, 0, 1, 1),
       (N'RCTS', N'RF Power Level', null, N'INT', null, 1, 2, 1, null, null, null, null, N'Common.PowerLevel',
        N'Setting.SRadio', 1, 0, 1, 1, 0, 0, 0, 1, 1),
       (N'RCTT', null, null, N'*', null, null, null, null, null, null, null, null, null, null, 1, 0, 0, 1, 0, 0, 0, 1,
        0),
       (N'RCTV', N'VSWR Value', null, N'FLOAT', null, null, null, null, null, null, null, null, null,
        N'Event.Transmission', 1, 0, 1, 0, 1, 0, 0, 1, 1),
       (N'RCTW', N'VSWR LED', null, N'INT', null, null, null, null, null, null, null, null, null, N'Event.Transmission',
        1, 0, 1, 0, 1, 0, 0, 1, 1);
GO
INSERT INTO RCMS.Command.KeyInformation (CKey, TX_Name, RX_Name, Parameter_Type, Parameter_Unit, INT_Parameter_Min,
                                         INT_Parameter_Max, INT_Parameter_Step, FLOAT_Parameter_Min,
                                         FLOAT_Parameter_Max, FLOAT_Parameter_Step, STRING_Max_Length, Convertor_Table,
                                         RegisterTable, TX_Support, RX_Support, GET_Support, SET_Support, TRAP_Support,
                                         GET_Need_Value, Update_Need_Restart, Work_As_Expected, Fully_Identified)
VALUES (N'RCVV', N'External VSWR Voltage', null, N'FLOAT', null, null, null, null, null, null, null, null, null,
        N'Event.Transmission', 1, 0, 1, 0, 1, 0, 0, 1, 1),
       (N'RIPC', N'PTT Input Configuration', null, N'INT', null, null, null, null, null, null, null, null,
        N'Common.PTTConfiguration', N'Setting.SRadio', 1, 0, 1, 1, 0, 0, 1, 1, 1),
       (N'RIRC', null, N'RSSI Output Curve', N'*', null, null, null, null, null, null, null, null, null,
        N'Event.ERadio', 0, 1, 1, 1, 1, 0, 0, 1, 1),
       (N'RIRO', null, N'RSSI Output Type', N'INT', null, null, null, null, null, null, null, null,
        N'Common.RSSIOutput', N'Setting.SRadio', 0, 1, 1, 1, 0, 0, 1, 1, 1),
       (N'RIVL', N'EXT VSWR limit', null, N'FLOAT', N'Volt', null, null, null, 0.0, 5.0, 0.1, null, null,
        N'Setting.SRadio', 1, 0, 1, 1, 0, 0, 1, 1, 1),
       (N'RIVP', N'EXT VSWR Polarity', null, N'INT', null, null, null, null, null, null, null, null,
        N'Common.EVSWRPolarity', N'Setting.SRadio', 1, 0, 1, 1, 0, 0, 1, 1, 1),
       (N'RUFL', N'FTP Login', N'FTP Login', N'*', null, null, null, null, null, null, null, null, null,
        N'Setting.SRadio', 1, 1, 1, 1, 0, 0, 1, 1, 1),
       (N'RUFP', N'FTP Password', N'FTP Password', N'*', null, null, null, null, null, null, null, null, null,
        N'Setting.SRadio', 1, 1, 1, 1, 0, 0, 1, 1, 1),
       (N'RUSI', null, null, N'INT', null, null, null, null, null, null, null, null, null, null, 1, 1, 1, 1, 0, 0, 0, 1,
        0),
       (N'RUUS', null, null, N'*', null, null, null, null, null, null, null, null, null, null, 1, 1, 1, 0, 0, 0, 0, 1,
        0);
GO
INSERT INTO RCMS.Command.KeyInformation (CKey, TX_Name, RX_Name, Parameter_Type, Parameter_Unit, INT_Parameter_Min,
                                         INT_Parameter_Max, INT_Parameter_Step, FLOAT_Parameter_Min,
                                         FLOAT_Parameter_Max, FLOAT_Parameter_Step, STRING_Max_Length, Convertor_Table,
                                         RegisterTable, TX_Support, RX_Support, GET_Support, SET_Support, TRAP_Support,
                                         GET_Need_Value, Update_Need_Restart, Work_As_Expected, Fully_Identified)
VALUES (N'SCPG', N'Ping Timeout', N'Ping Timeout', N'INT', null, null, null, null, null, null, null, null, null,
        N'Event.ERadio', 1, 1, 1, 1, 0, 0, 0, 1, 1),
       (N'SCSL', N'Session List', N'Session List', N'*', null, null, null, null, null, null, null, null, null,
        N'Event.Session', 1, 1, 1, 0, 1, 0, 0, 1, 1),
       (N'SCSS', N'Session Type', N'Session Type', N'INT', null, null, null, null, null, null, null, null,
        N'Common.SessionType', N'Event.ERadio', 1, 1, 1, 1, 1, 0, 0, 1, 1),
       (N'STBC', null, null, N'*', null, null, null, null, null, null, null, null, null, null, 1, 1, 0, 1, 0, 0, 0, 1,
        0),
       (N'STCT', null, null, N'*', null, null, null, null, null, null, null, null, null, null, 1, 1, 0, 1, 0, 0, 0, 1,
        0),
       (N'STEC', null, null, N'*', null, null, null, null, null, null, null, null, null, null, 1, 1, 0, 1, 0, 0, 0, 1,
        0),
       (N'STEN', null, null, N'*', null, null, null, null, null, null, null, null, null, null, 1, 1, 0, 1, 0, 0, 0, 1,
        0),
       (N'STEU', null, null, N'*', null, null, null, null, null, null, null, null, null, null, 1, 1, 0, 1, 0, 0, 0, 1,
        0),
       (N'STSF', null, null, N'*', null, null, null, null, null, null, null, null, null, null, 1, 1, 0, 1, 0, 0, 0, 1,
        0),
       (N'VOAC', null, null, N'*', null, null, null, null, null, null, null, null, null, null, 1, 1, 0, 1, 0, 0, 0, 1,
        0);
GO
INSERT INTO RCMS.Command.KeyInformation (CKey, TX_Name, RX_Name, Parameter_Type, Parameter_Unit, INT_Parameter_Min,
                                         INT_Parameter_Max, INT_Parameter_Step, FLOAT_Parameter_Min,
                                         FLOAT_Parameter_Max, FLOAT_Parameter_Step, STRING_Max_Length, Convertor_Table,
                                         RegisterTable, TX_Support, RX_Support, GET_Support, SET_Support, TRAP_Support,
                                         GET_Need_Value, Update_Need_Restart, Work_As_Expected, Fully_Identified)
VALUES (N'VOAN', null, null, N'*', null, null, null, null, null, null, null, null, null, null, 1, 1, 0, 1, 0, 0, 0, 1,
        0),
       (N'VOAP', null, null, N'*', null, null, null, null, null, null, null, null, null, null, 1, 1, 0, 1, 0, 0, 0, 1,
        0),
       (N'VOCD', null, null, N'*', null, null, null, null, null, null, null, null, null, null, 1, 1, 0, 1, 0, 0, 0, 1,
        0),
       (N'VODS', null, null, N'*', null, null, null, null, null, null, null, null, null, null, 1, 1, 0, 1, 0, 0, 0, 1,
        0),
       (N'VOJB', null, null, N'*', null, null, null, null, null, null, null, null, null, null, 1, 1, 0, 1, 0, 0, 0, 1,
        0),
       (N'VOLS', null, null, N'*', null, null, null, null, null, null, null, null, null, null, 1, 1, 0, 1, 0, 0, 0, 1,
        0),
       (N'VOMS', null, null, N'*', null, null, null, null, null, null, null, null, null, null, 1, 1, 0, 1, 0, 0, 0, 1,
        0),
       (N'VORP', null, null, N'*', null, null, null, null, null, null, null, null, null, null, 1, 1, 0, 1, 0, 0, 0, 1,
        0),
       (N'VOSC', null, null, N'*', null, null, null, null, null, null, null, null, null, null, 1, 1, 0, 1, 0, 0, 0, 1,
        0),
       (N'VOSM', null, null, N'*', null, null, null, null, null, null, null, null, null, null, 1, 1, 0, 1, 0, 0, 0, 1,
        0),
       (N'VREN', null, null, N'*', null, null, null, null, null, null, null, null, null, null, 1, 1, 0, 1, 0, 0, 0, 1,
        0),
       (N'VRRC', null, null, N'*', null, null, null, null, null, null, null, null, null, null, 1, 1, 0, 1, 0, 0, 0, 1,
        0);
GO
