INSERT INTO RCMS.Django.guardian_groupobjectpermission (object_pk, content_type_id, group_id, permission_id) VALUES (N'31', 6, 10, 25);
INSERT INTO RCMS.Django.guardian_groupobjectpermission (object_pk, content_type_id, group_id, permission_id) VALUES (N'32', 6, 10, 25);
INSERT INTO RCMS.Django.guardian_groupobjectpermission (object_pk, content_type_id, group_id, permission_id) VALUES (N'1', 6, 10, 307);
INSERT INTO RCMS.Django.guardian_groupobjectpermission (object_pk, content_type_id, group_id, permission_id) VALUES (N'9', 6, 10, 308);
INSERT INTO RCMS.Django.guardian_groupobjectpermission (object_pk, content_type_id, group_id, permission_id) VALUES (N'2', 6, 10, 309);
INSERT INTO RCMS.Django.guardian_groupobjectpermission (object_pk, content_type_id, group_id, permission_id) VALUES (N'31', 6, 10, 309);
INSERT INTO RCMS.Django.guardian_groupobjectpermission (object_pk, content_type_id, group_id, permission_id) VALUES (N'72', 6, 6, 307);
INSERT INTO RCMS.Django.guardian_groupobjectpermission (object_pk, content_type_id, group_id, permission_id) VALUES (N'72', 6, 6, 25);
INSERT INTO RCMS.Django.guardian_groupobjectpermission (object_pk, content_type_id, group_id, permission_id) VALUES (N'72', 6, 6, 309);
