from pymssql import _mssql as db
from create_database import get_connection


class PermissionQuery:
    def __init__(self):
        self.permissions = {
            'AIAD': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 1, 0),
                     'Operator': (1, 1, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'AIAI': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 0, 0),
                     'Operator': (0, 0, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'AICA': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 0, 0),
                     'Operator': (0, 0, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'AIEL': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 0, 0),
                     'Operator': (0, 0, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'AIGA': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 0, 0),
                     'Operator': (0, 0, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'AILA': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 1, 0),
                     'Operator': (1, 1, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'AIML': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 0, 0),
                     'Operator': (0, 0, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'AISE': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 0, 0),
                     'Operator': (0, 0, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'AISF': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 0, 0),
                     'Operator': (0, 0, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'AISL': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 0, 0),
                     'Operator': (0, 0, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'AITP': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 0, 0),
                     'Operator': (0, 0, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'AITS': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 0, 0),
                     'Operator': (0, 0, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'ERBE': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 0, 0),
                     'Operator': (0, 0, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'ERGN': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 0, 0),
                     'Operator': (0, 0, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'EVCL': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 0, 0),
                     'Operator': (0, 0, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'EVEE': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 0, 0),
                     'Operator': (0, 0, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'EVEL': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 0, 0),
                     'Operator': (0, 0, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'EVSR': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 0, 0),
                     'Operator': (0, 0, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'FFBL': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 0, 0),
                     'Operator': (0, 0, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'FFCO': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 1, 0),
                     'Operator': (0, 0, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'FFEA': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 0, 0),
                     'Operator': (0, 0, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'FFFC': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 0, 0),
                     'Operator': (0, 0, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'FFFE': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 0, 0),
                     'Operator': (0, 0, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'FFLM': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 0, 0),
                     'Operator': (0, 0, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'FFLT': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 0, 0),
                     'Operator': (0, 0, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'FFMD': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 0, 0),
                     'Operator': (0, 0, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'FFRS': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 0, 0),
                     'Operator': (0, 0, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'FFSC': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 0, 0),
                     'Operator': (0, 0, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'FFSL': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 1, 0),
                     'Operator': (0, 0, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'FFSN': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 1, 0),
                     'Operator': (1, 1, 1, 0),
                     'Observer': (0, 0, 0, 0)},
            'FFSP': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 0, 0),
                     'Operator': (0, 0, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'FFSQ': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 1, 0),
                     'Operator': (1, 1, 1, 0),
                     'Observer': (0, 0, 0, 0)},
            'FFSR': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 1, 0),
                     'Operator': (1, 1, 1, 0),
                     'Observer': (0, 0, 0, 0)},
            'FFTO': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 1, 0),
                     'Operator': (1, 1, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'FFTR': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 1, 0),
                     'Operator': (0, 0, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'GRAC': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 1, 0),
                     'Operator': (0, 0, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'GRAS': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 0, 0),
                     'Operator': (0, 0, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'GRAT': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 0, 0),
                     'Operator': (0, 0, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'GRBS': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 0, 0),
                     'Operator': (0, 0, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'GRCO': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 0, 0),
                     'Operator': (0, 0, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'GRCS': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 0, 0),
                     'Operator': (0, 0, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'GRDH': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 0, 0),
                     'Operator': (0, 0, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'GRDN': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 0, 0),
                     'Operator': (0, 0, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'GRDS': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 0, 0),
                     'Operator': (0, 0, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'GREX': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 0, 0),
                     'Operator': (0, 0, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'GRHN': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 0, 0),
                     'Operator': (0, 0, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'GRIE': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 0, 0),
                     'Operator': (0, 0, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'GRII': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 0, 0),
                     'Operator': (0, 0, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'GRIL': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 0, 0),
                     'Operator': (0, 0, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'GRIN': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 0, 0),
                     'Operator': (0, 0, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'GRIP': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 0, 0),
                     'Operator': (0, 0, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'GRIS': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 1, 0),
                     'Operator': (1, 1, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'GRIV': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 0, 0),
                     'Operator': (0, 0, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'GRLO': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 0, 0),
                     'Operator': (0, 0, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'GRLR': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 1, 0),
                     'Operator': (1, 1, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'GRLT': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 1, 0),
                     'Operator': (1, 1, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'GRME': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 1, 0),
                     'Operator': (0, 0, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'GRNA': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 0, 0),
                     'Operator': (0, 0, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'GRNC': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 0, 0),
                     'Operator': (0, 0, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'GRND': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 0, 0),
                     'Operator': (0, 0, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'GRNS': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 0, 0),
                     'Operator': (0, 0, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'GRSE': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 0, 0),
                     'Operator': (0, 0, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'GRSN': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 0, 0),
                     'Operator': (0, 0, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'GRSV': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 0, 0),
                     'Operator': (0, 0, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'GRTI': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 0, 0),
                     'Operator': (0, 0, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'GRUI': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 0, 0),
                     'Operator': (0, 0, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'GRVE': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 0, 0),
                     'Operator': (0, 0, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'MSAC': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 0, 0),
                     'Operator': (0, 0, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'MSGO': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 0, 0),
                     'Operator': (0, 0, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'MSTY': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 0, 0),
                     'Operator': (0, 0, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'RCDP': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 0, 0),
                     'Operator': (0, 0, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'RCIT': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 1, 0),
                     'Operator': (1, 1, 1, 0),
                     'Observer': (0, 0, 0, 0)},
            'RCLP': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 1, 0),
                     'Operator': (1, 1, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'RCLR': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 0, 0),
                     'Operator': (0, 0, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'RCLV': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 0, 0),
                     'Operator': (0, 0, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'RCMG': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 1, 0),
                     'Operator': (0, 0, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'RCMO': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 0, 0),
                     'Operator': (0, 0, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'RCMV': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 0, 0),
                     'Operator': (0, 0, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'RCNP': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 1, 0),
                     'Operator': (1, 1, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'RCOC': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 0, 0),
                     'Operator': (0, 0, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'RCPF': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 0, 0),
                     'Operator': (0, 0, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'RCPP': {'Administrator': (1, 1, 1, 1), 'Expert': (0, 0, 0, 0), 'Supervisor': (0, 0, 0, 0),
                     'Operator': (0, 0, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'RCPT': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 0, 0),
                     'Operator': (0, 0, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'RCPV': {'Administrator': (1, 1, 1, 1), 'Expert': (0, 0, 0, 0), 'Supervisor': (0, 0, 0, 0),
                     'Operator': (0, 0, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'RCRI': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 0, 0),
                     'Operator': (0, 0, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'RCRR': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 0, 0),
                     'Operator': (0, 0, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'RCTC': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 0, 0),
                     'Operator': (0, 0, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'RCTO': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 0, 0),
                     'Operator': (0, 0, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'RCTP': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 0, 0),
                     'Operator': (0, 0, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'RCTS': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 1, 0),
                     'Operator': (1, 1, 1, 0),
                     'Observer': (0, 0, 0, 0)},
            'RCTV': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 0, 0),
                     'Operator': (0, 0, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'RCTW': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 0, 0),
                     'Operator': (0, 0, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'RCVV': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 0, 0),
                     'Operator': (0, 0, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'RIPC': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 0, 0),
                     'Operator': (0, 0, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'RIRC': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 0, 0),
                     'Operator': (0, 0, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'RIRO': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 0, 0),
                     'Operator': (0, 0, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'RIVL': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 0, 0),
                     'Operator': (0, 0, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'RIVP': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 0, 0),
                     'Operator': (0, 0, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'RUFL': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 0, 0),
                     'Operator': (0, 0, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'RUFP': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 0, 0),
                     'Operator': (0, 0, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'SCPG': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 0, 0),
                     'Operator': (0, 0, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'SCSL': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 0, 0),
                     'Operator': (0, 0, 0, 0),
                     'Observer': (0, 0, 0, 0)},
            'SCSS': {'Administrator': (1, 1, 1, 1), 'Expert': (1, 1, 1, 1), 'Supervisor': (1, 1, 0, 0),
                     'Operator': (0, 0, 0, 0),
                     'Observer': (0, 0, 0, 0)},
        }
        self.connection = get_connection(to_liara=True)
        self.code_names = ['send_command', 'get_command', 'set_command', 'trap_command']
        self.ckey_id, self.permission_id, self.table_id, self.groups = self.get_data()
        self.database = 'USE RCMS;\nGO\n\n'
        self.query = 'INSERT INTO Django.guardian_groupobjectpermission\n    ' \
                     '(object_pk, content_type_id, group_id, permission_id)\nVALUES\n{}'

        self.output_file = r'D:\Hadi\Projects\RDB\dbfiles\Database Creation\33_Fill_Group_Permissions.sql'
        print(self.ckey_id)
        print(self.permission_id)
        print(self.table_id)
        print(self.groups)

    def get_data(self):
        query = "select id, CKey FROM RCMS.Django.account_sendkeycommand"
        self.connection.execute_query(query)
        key_id = {row['CKey']: row['id'] for row in self.connection}
        permission_name = ['send_command', 'get_command', 'set_command', 'trap_command']
        table_id, permission = 0, {}
        query = "select id, content_type_id from RCMS.Django.auth_permission where codename='{}'"

        for cn in permission_name:
            self.connection.execute_query(query.format(cn))
            ans = list(self.connection)[0]
            permission[cn], c = ans['id'], ans['content_type_id']
            if table_id == 0:
                table_id = c
            elif table_id != c:
                print('Error!')
                exit()

        query = "select id, name from RCMS.Django.auth_group"
        self.connection.execute_query(query)
        groups = {row['name']: row['id'] for row in self.connection}
        return key_id, permission, table_id, groups

    # print(codes)
    # print(content_id)
    # codes = {connection.execute_scalar(query.format(cn)) for cn in code_names}

    def save_query(self):
        with open(self.output_file, 'w') as file:
            file.write(self.database)
            line = f"    ({{}}, {self.table_id}, {{}}, {{}}),\n"
            for key, group_permissions in self.permissions.items():
                values = ""
                for group, permission in group_permissions.items():
                    send_p, get_p, set_p, trap_p = permission
                    obj_pk = self.ckey_id.get(key)
                    grp_id = self.groups.get(group)
                    if send_p == 1:
                        values += line.format(obj_pk, grp_id, self.permission_id.get('send_command'))
                    if get_p == 1:
                        values += line.format(obj_pk, grp_id, self.permission_id.get('get_command'))
                    if set_p == 1:
                        values += line.format(obj_pk, grp_id, self.permission_id.get('set_command'))
                    if trap_p == 1:
                        values += line.format(obj_pk, grp_id, self.permission_id.get('trap_command'))
                file.write(self.query.format(values)[:-2] + ';\nGO\n\n')


pq = PermissionQuery()
pq.save_query()
