
BACKUP LOG [RCMS] TO DISK = N'/var/opt/mssql/backup/RCMS_Log.trn' WITH COMPRESSION, NOFORMAT, NOINIT, NAME = N'RCMS-Transaction Log Backup', SKIP, NOREWIND, NOUNLOAD, STATS = 10
GO
BACKUP DATABASE [RCMS] TO DISK = N'/var/opt/mssql/backup/RCMS_Full.bak' WITH COMPRESSION, NOFORMAT, NOINIT, NAME = N'RCMS-Full Database Backup', SKIP, NOREWIND, NOUNLOAD, STATS = 10
GO

ALTER DATABASE RCMS SET RECOVERY SIMPLE
GO
DBCC SHRINKFILE (نام_فایل_لاگ, 1)
GO
ALTER DATABASE RCMS SET RECOVERY FULL
