INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (1, 0, N'RESTART', 0, 0);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (2, 0, N'TIME CHANGED', 0, 0);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (3, 0, N'EVENT LIST FULL', 0, 0);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (101, 1, N'INACTIVE WARNING', 2, 3);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (102, 2, N'NOGO ERROR', 0, 0);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (103, 1, N'MAIN FAN WARNING', 4, 6);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (104, 2, N'MAIN FAN ERROR', 0, 0);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (107, 1, N'MMI WD RESTART', 0, 0);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (108, 1, N'OCXO OVEN WARNING', 0, 0);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (109, 1, N'MODE IMPOSSIBLE', 0, 0);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (110, 0, N'MMI PART', 0, 0);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (201, 1, N'PSU FAN WARNING', 4, 6);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (202, 2, N'PSU FAN ERROR', 0, 0);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (203, 1, N'PSU TEMP WARNING', 0, 0);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (204, 2, N'PSU TEMP ERROR', 0, 0);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (301, 1, N'TX DC BATTERY', 2, 7);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (302, 1, N'TX AC MAIN', 1, 7);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (303, 1, N'PA DC 28V VLT LOW', 0, 0);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (304, 2, N'PA DC 28V OVERVOLT', 0, 0);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (305, 2, N'PA DC 28V UNDERVOLT', 0, 0);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (306, 2, N'TX DC 1.2V FAIL', 0, 0);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (307, 2, N'TX DC 1.8V FAIL', 0, 0);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (308, 2, N'TX DC 5.7V FAIL', 0, 0);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (309, 2, N'TX DC 8.7V FAIL', 0, 0);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (310, 2, N'TX DC 28V FAIL', 0, 0);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (311, 2, N'TX DC 28V PTT FAIL', 0, 0);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (312, 2, N'TX DC -48V PTT FAIL', 0, 0);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (313, 2, N'TX DC -11V FAIL', 0, 0);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (314, 2, N'TX DC -5.7V FAIL', 0, 0);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (315, 2, N'TX INT REF UNLOCK', 0, 0);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (316, 2, N'TX SYNTH UNLOCK', 0, 0);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (317, 1, N'PA TEMP WARNING', 0, 0);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (318, 2, N'PA TEMP ERROR', 0, 0);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (319, 1, N'TX TEMP WARNING', 0, 0);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (320, 2, N'TX TEMP ERROR', 0, 0);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (321, 2, N'PA NO OUTPUT PWR', 0, 0);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (322, 1, N'PA POWER LOW -1DB', 0, 0);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (323, 1, N'PA POWER LOW -3DB', 4, 6);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (324, 2, N'PA POWER HIGH 1DB', 0, 0);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (325, 1, N'PA POWER REDUCED DC', 0, 0);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (326, 1, N'PA PWR REDUCED VSWR', 0, 0);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (327, 1, N'PA PWR REDUCED TEMP', 0, 0);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (328, 1, N'PWR REDUCED PSU TEMP', 0, 0);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (329, 1, N'TX IQ OVERLOAD', 0, 0);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (330, 2, N'TX IQ LOOP UNLOCK', 0, 0);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (331, 1, N'PA VSWR ABOVE 2', 4, 6);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (332, 1, N'TX WD RESTART', 0, 0);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (333, 2, N'TX DSP ERROR', 0, 0);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (334, 2, N'TX NO MMI CONNECT', 0, 0);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (335, 1, N'TX USB CONNECT', 2, 3);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (336, 1, N'TX LOCAL MODE', 2, 3);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (337, 1, N'TX PTT TIMEOUT EXPIR', 0, 0);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (338, 1, N'TX EXT VSWR HIGH X7', 1, 7);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (339, 1, N'EXT FILTER TIMEOUT', 0, 0);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (340, 1, N'EXT FILTER ALARM', 0, 0);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (341, 1, N'EXT FILTER LOCAL', 0, 0);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (342, 1, N'USER CONTACT WARNING', 1, 3);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (343, 1, N'TX SNMPD WD RESTART', 0, 0);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (344, 1, N'BOOT ERROR', 0, 0);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (345, 2, N'TX E1 LOS', 1, 5);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (346, 2, N'TX E1 LOF', 1, 5);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (347, 1, N'TX E1 RAI', 2, 6);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (348, 1, N'TX E1 CRC4 ERROR', 2, 6);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (349, 1, N'EXT PA ALARM', 0, 0);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (350, 1, N'PWR REDUCED TO LOW', 0, 0);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (351, 0, N'TX PART', 0, 0);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (352, 0, N'TX RST REQ RC', 0, 0);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (353, 1, N'TX NTP SYNC LOST', 0, 0);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (354, 1, N'TX REC CONNECT FAIL', 0, 0);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (401, 1, N'RX DC BATTERY', 2, 7);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (402, 1, N'RX AC MAIN', 1, 7);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (403, 1, N'RX DC 28V VLT LOW', 0, 0);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (404, 2, N'RX DC 28V OVERVOLT', 0, 0);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (405, 2, N'RX INT REF UNLOCK', 0, 0);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (406, 1, N'RX RF OVERLOAD', 0, 0);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (407, 1, N'RX IF OVERLOAD', 0, 0);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (408, 2, N'RX DSP ERROR', 0, 0);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (409, 1, N'RX WD RESTART', 0, 0);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (410, 2, N'RX SYNTH UNLOCK', 0, 0);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (411, 1, N'RX TEMP WARNING', 0, 0);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (412, 2, N'RX TEMP ERROR', 0, 0);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (413, 2, N'RX NO MMI CONNECT', 0, 0);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (414, 1, N'RX USB CONNECT', 2, 3);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (415, 1, N'RX LOCAL MODE', 2, 3);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (416, 2, N'RX DC 1.2V FAIL', 0, 0);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (417, 2, N'RX DC 1.25V FAIL', 0, 0);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (418, 2, N'RX DC 3.3V FAIL', 0, 0);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (419, 2, N'RX DC 4.0V FAIL', 0, 0);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (420, 2, N'RX DC 13V FAIL', 0, 0);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (421, 2, N'RX DC 5.7V FAIL', 0, 0);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (422, 2, N'RX DC 8.7V FAIL', 0, 0);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (423, 2, N'RX DC 28V FAIL', 0, 0);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (424, 2, N'RX DC -20V FAIL', 0, 0);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (425, 2, N'RX DC -11V FAIL', 0, 0);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (426, 2, N'RX DC -5.7V FAIL', 0, 0);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (427, 1, N'EXT FILTER TIMEOUT', 0, 0);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (428, 1, N'EXT FILTER ALARM', 0, 0);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (429, 1, N'EXT FILTER LOCAL', 0, 0);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (430, 1, N'USER CONTACT WARNING', 1, 3);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (431, 1, N'RX SNMPD WD RESTART', 0, 0);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (433, 1, N'CONGESTION TIMEOUT', 0, 0);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (434, 1, N'BOOT ERROR', 0, 0);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (435, 2, N'RX E1 LOS', 1, 5);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (436, 2, N'RX E1 LOF', 1, 5);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (437, 1, N'RX E1 RAI', 2, 6);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (438, 1, N'RX E1 CRC4 ERROR', 2, 6);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (439, 0, N'RX PART', 0, 0);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (440, 0, N'RX RST REQ RC', 0, 0);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (445, 1, N'RX NTP SYNC LOST', 0, 0);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (446, 0, N'STD', 0, 0);
INSERT INTO RCMS.Common.CBITList (CBIT_Code, Level, Description, Configuration, Selectable) VALUES (447, 1, N'RX REC CONNECT FAIL', 0, 0);
